version: '3'

services: 
  api:
    build: .
    volumes:
      - "./server:/app"
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    # links:
    #   - mongo
    networks:
      - mongo-compose-network

  client:
    build: .
    volumes:
      - "./web:/app"
    ports:
      - "3000:3000"
    depends_on:
      - api
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
